name: Deploy signaling server to Google Cloud
on:
  push:
    branches:
      - master
    paths:
      - signaling-app/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Restore yarn cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Login to gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    
    - name: Install, build and deploy
      run: |
        cd signaling-app
        yarn install
        yarn build
        cd dist
        gcloud app deploy --project=light-footing-262920