name: Deploy signaling app to Fly
on:
  push:
    branches:
      - master
    paths:
      - signaling-app-v2/**
jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # This step runs `flyctl deploy`.
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_PROJECT_PATH: signaling-app-v2  
        with:
          args: "deploy"
