name: Compile rust, deploy to DO droplet
on:
  push:
    branches:
      - master
    paths:
      - signaling-app-rust/**
      - ./github/workflows/signaling-app-rust-droplet.yml
jobs:
  build-and-deploy:
    name: Compile rust, deploy to DO droplet
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
      - uses: Swatinem/rust-cache@v1
        with: 
          working-directory: signaling-app-rust
      - name: Compile Rust
        run: |
          cd signaling-app-rust
          cargo build --release
      - name: Deploy and start binary
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_ADDRESS }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: signaling-app/rust/target/release/signaling-app-rust
          target: signaling-app/rust
          strip-components: 4
          overwrite: true
