name: Deploy signaling server to Azure web app
on:
  push:
    branches:
      - master
    paths:
      - signaling-app/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install, build and deploy
      run: |
        cd signaling-app
        yarn install
        yarn build
    
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: snake-signals
        package: dist
        publish-profile: ${{ secrets.AZURE_DEPLOYMENT_PROFILE }}